--- 
- hosts: local 
  name: Installing monitoring server 
  tasks: 
    - include_tasks: prerequisites.yml 
    - include_tasks: docker_install.yaml
    - include_tasks: node_exporter_install.yml 
    - include_tasks: node_exporter_service_install.yml 
    - include_tasks: sensors_install.yml 
    - include_tasks: cadvisor_install.yml 
    - include_tasks: blackbox_exporter_install.yml
    - include_tasks: prometheus_install.yml 
    - include_tasks: grafana_install.yml 

- hosts: distant 
  name: Installing Distant Exporter 
  tasks: 
    - include_tasks: prerequisites.yml 
    - include_tasks: node_exporter_install.yml 
    - include_tasks: node_exporter_service_install.yml 
    - include_tasks: sensors_install.yml 
    - include_tasks: cadvisor_install.yml 
