---
- name: Create Share Folder 1/2
  become: true
  file:
    path: /home/docker_share/prometheus
    owner: "{{ ansible_user }}"
    mode: 0775
    state: directory

- name: Create Share Folder 2/2
  become: true
  file:
    path: /home/docker_share/data/prometheus
    mode: 0775
    owner: "{{ ansible_user }}"
    state: directory

- name: Copie conf file for Prometheus
  become: true
  template:
    src: conf/prometheus/prometheus.yml
    dest: /home/docker_share/prometheus/prometheus.yml
    owner: "{{ ansible_user }}"
    mode: 0775

- name: Start Prometheus Container
  become: true
  docker_container:
    name: prometheus
    image: quay.io/prometheus/prometheus:v2.0.0
    user: 1000:2000
    volumes: 
      - "/home/docker_share/prometheus:/etc/prometheus:rw"
      - "/home/docker_share/data/prometheus:/prometheus:rw"
    restart_policy: always
    published_ports: 9090:9090
    command: "--web.enable-lifecycle --config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus --web.console.libraries=/usr/share/prometheus/console_libraries --web.console.templates=/usr/share/prometheus/consoles"
    state: started
